--- # install git on Centos target hosts
- hosts: centosservers
  become: yes
  gather_facts: False
  tasks:
  - name: install git CentOS
    yum:
      name: git
      state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
