--- #install updates on SLES target hosts
- hosts: testsles
  become: yes
  tasks:
  - name: install updates SUSE
    zypper:
      name: "*"
      state: latest
    when: ansible_distribution == 'SUSE' or ansible_distribution == 'SLES'