--- #Install nginx on target host
- hosts: nginxcentos
  become: yes
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest
  - name: enable and start nginx
    service:
      name: nginx
      state: started
      enabled: yes
    become: yes
  - name: copy the content of the web site
    copy:
      src: /home/ansible/ansibledemo/playbooks/prod/nginx/static-site-src/
      dest: /usr/share/nginx/html/
  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes
