--- # install nginx on target host
- hosts: nginxsles
  become: yes
  tasks:
  - name: install nginx
    zypper:
      name: nginx
      state: latest
  - name: enable and start nginx
    service:
      name: nginx
      state: started
      enabled: yes
    become: yes
  - name: copy the content of the web site
    copy:
      src: /home/ansible/ansibledemo/playbooks/prod/nginx/static-site-src/index.html
      dest: /srv/www/htdocs/
  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes
